// Trade-personalized on-site checklist starters. Keyed by the client-facing
// service label (client_requests.service_needed). A pro taps "Load suggested
// checklist" on a job and gets a best-practices list for that trade instead of
// a blank page — they can add/remove/reword anything before saving.

const GENERIC: string[] = [
  "Confirm scope with the client before starting",
  "Photograph the area before work begins",
  "Protect floors and surrounding surfaces",
  "Complete the agreed work",
  "Test / verify everything works",
  "Clean up the work area and remove debris",
  "Walk the client through what was done",
  "Take after photos",
];

const TEMPLATES: Record<string, string[]> = {
  "General Handyman": [
    "Confirm the task list with the client",
    "Photograph each area before starting",
    "Protect floors and nearby furniture",
    "Complete each repair on the list",
    "Test everything you touched (doors, fixtures, mounts)",
    "Clean up and remove all debris",
    "Walk the client through the finished work",
    "Take after photos",
  ],
  "Plumbing Repair": [
    "Locate and confirm the water shut-off",
    "Photograph the problem area before starting",
    "Protect flooring around the work area",
    "Complete the repair / install",
    "Check every joint for leaks under pressure",
    "Run water 5+ minutes and re-check for drips",
    "Restore water and verify hot/cold at fixtures",
    "Clean up and take after photos",
  ],
  "Electrical Work": [
    "Turn off the breaker and verify the circuit is dead",
    "Photograph existing wiring before changes",
    "Complete the wiring / install to code",
    "Secure all connections and box covers",
    "Restore power and test every device installed",
    "Test GFCI / breaker function where applicable",
    "Label the panel if circuits changed",
    "Clean up and take after photos",
  ],
  "HVAC Maintenance": [
    "Confirm system symptoms with the client",
    "Inspect and replace the filter if needed",
    "Check thermostat operation",
    "Inspect blower, motor and belts",
    "Check for unusual noise or vibration",
    "Verify heating/cooling output after service",
    "Show the client the filter size for next time",
    "Clean up and take after photos",
  ],
  "Carpentry": [
    "Confirm measurements and materials with the client",
    "Photograph the area before starting",
    "Protect surrounding surfaces",
    "Cut and fit — measure twice",
    "Fasten, level and square everything",
    "Sand and finish edges",
    "Clean up sawdust and offcuts",
    "Walk the client through and take after photos",
  ],
  "Painting": [
    "Confirm colours and sheen with the client",
    "Photograph rooms before starting",
    "Tape edges and mask fixtures",
    "Cover floors and furniture",
    "Patch and sand imperfections first",
    "Prime where needed",
    "Apply coats with proper dry time",
    "Remove tape, touch up, clean up, after photos",
  ],
  "Drywall / Flooring": [
    "Confirm scope and materials with the client",
    "Photograph the area before starting",
    "Protect adjacent rooms from dust",
    "Complete the install / patch",
    "Sand and feather joints smooth (drywall)",
    "Check for lippage and gaps (flooring)",
    "Clean up dust and offcuts",
    "Take after photos",
  ],
  "Oil Change": [
    "Confirm oil type and filter for the vehicle",
    "Warm up the engine briefly",
    "Drain old oil completely",
    "Replace the oil filter",
    "Refill to spec and check the level",
    "Check for leaks after running the engine",
    "Reset the oil-life monitor",
    "Record the mileage for next service",
  ],
  "Tire Swap / Rotation": [
    "Check tread depth and condition on all tires",
    "Note any uneven wear patterns for the client",
    "Torque all lug nuts to spec",
    "Set tire pressures to the door-jamb spec",
    "Check the spare's condition and pressure",
    "Remind the client to re-torque after 50–100 km",
  ],
  "Battery / Brakes": [
    "Test battery voltage and charging system",
    "Clean terminals and check connections",
    "Inspect pads, rotors and lines",
    "Complete the replacement",
    "Test-drive and verify braking feel",
    "Check for warning lights after service",
  ],
  "Vehicle Maintenance": [
    "Confirm the service list with the client",
    "Check all fluid levels",
    "Inspect belts, hoses and battery",
    "Complete the agreed services",
    "Check tire pressures and lights",
    "Test drive and verify no warning lights",
    "Record mileage and recommend next service",
  ],
  "Landscaping": [
    "Walk the yard with the client and confirm scope",
    "Photograph before starting",
    "Call/check for buried lines before digging",
    "Complete the agreed work",
    "Haul away or bag all green waste",
    "Rake and tidy the whole work area",
    "Water new plantings if applicable",
    "Take after photos",
  ],
  "Snow Removal": [
    "Clear driveway and walkways fully",
    "Clear the city sidewalk (bylaw requirement)",
    "Apply ice melt / gravel on slick spots",
    "Clear in front of the mailbox and gas meter",
    "Don't pile snow against the foundation or on the street",
    "Take after photos",
  ],
  "Gutters": [
    "Photograph gutters before starting",
    "Remove all debris from gutters",
    "Flush gutters and check flow",
    "Check and clear all downspouts",
    "Check fasteners and slope, note any damage",
    "Bag and remove all debris",
    "Take after photos",
  ],
  "Windows & Doors": [
    "Confirm measurements before removal",
    "Photograph the existing unit",
    "Remove the old unit carefully",
    "Install plumb, level and square",
    "Insulate and seal the perimeter",
    "Test operation and locks",
    "Caulk exterior joints",
    "Clean glass and take after photos",
  ],
  "Siding & Roofing": [
    "Photograph the area before starting",
    "Set up fall protection / ladder safety",
    "Remove damaged material",
    "Install new material to spec, flash and seal penetrations",
    "Check for hidden damage underneath and tell the client",
    "Magnet-sweep for nails around the house",
    "Haul away all debris",
    "Take after photos",
  ],
  "Garage": [
    "Confirm scope with the client",
    "Photograph before starting",
    "Complete the repair / install",
    "Test door balance and safety reverse (openers)",
    "Lubricate moving parts",
    "Test remotes and keypad",
    "Clean up and take after photos",
  ],
  "Air Conditioning": [
    "Confirm symptoms with the client",
    "Check and clean/replace the filter",
    "Clean the condenser coil",
    "Check refrigerant lines and insulation",
    "Verify cooling output at the vents",
    "Check condensate drain flow",
    "Clean up and take after photos",
  ],
  "Cleaning Services": [
    "Confirm rooms and priorities with the client",
    "Note any pre-existing damage before starting",
    "Clean top-to-bottom in each room",
    "Kitchen: appliances, counters, sink, floors",
    "Bathrooms: fixtures, glass, floors",
    "Empty all garbage bins",
    "Final walkthrough with the client",
  ],
  "Concrete / Masonry": [
    "Confirm scope and finish with the client",
    "Photograph before starting",
    "Check weather window for curing",
    "Prep and form the area properly",
    "Pour / lay and finish to spec",
    "Protect the work while it cures",
    "Clean tools and site",
    "Explain curing time to the client, after photos",
  ],
  "Locksmith": [
    "Verify the client's ID / right to access",
    "Photograph existing hardware",
    "Complete the rekey / install",
    "Test every key in every lock",
    "Test the door closes and latches smoothly",
    "Hand over all keys and count them with the client",
  ],
  "Appliance Repair / Install": [
    "Confirm make/model and the fault with the client",
    "Disconnect power / water / gas safely",
    "Photograph connections before removal",
    "Complete the repair / install",
    "Check for leaks (water/gas appliances)",
    "Run a full test cycle",
    "Level the appliance",
    "Clean up and take after photos",
  ],
};

// Suggested checklist for a job's service label — falls back to the generic
// best-practices list so "Load suggested checklist" always has something.
export function suggestedChecklist(serviceNeeded?: string | null): string[] {
  const first = (serviceNeeded || "").split(",")[0].trim();
  return TEMPLATES[first] ?? GENERIC;
}
